# IRC Server Configuration - Server A (Hub)

server:
  name: "VNSnet"
  host: "irc.vnsnet.se"
  port: 6667
  tls:
    enabled: true
    port: 7000
    cert_file: "certs/server.crt"
    key_file: "certs/server.key"
  
  max_clients: 1000
  timeout_seconds: 300
  ping_interval_seconds: 60

# WebSocket support
websocket:
  enabled: true
  host: "0.0.0.0"
  port: 8080
  allowed_origins:
    - "*"
  tls:
    enabled: false

# Server operators
operators:
  - name: "rAe"
    password: "$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy"  # "admin123"

# Logging
logging:
  level: "info"
  file: "logs/hub.log"
  console: true

# Channel settings
channels:
  max_per_user: 10
  persist_topics: false

# Server Linking - Hub Server
# 
# This server acts as a HUB - it ACCEPTS connections from leaf servers.
# Leaf servers will connect TO this server.
#
# To use:
# 1. Set linking.enabled to true
# 2. Choose a unique server_id (e.g., "001" for hub)
# 3. Set a STRONG password (share this with leaf admins)
# 4. Open firewall port for linking.port (default 7777)
# 5. Share these details with leaf server admins:
#    - Your server address (IP or domain)
#    - linking.port (7777)
#    - linking.password
#    - Your server_id ("0AA")
#    - Your server.name ("hub.example.net")
#
# No "links" section needed - leafs will connect to you!
#
linking:
  enabled: true
  host: "irc.vnsnet.se"                       # Listen on all interfaces for server links
  port: 7777                             # Port for server-to-server connections
  server_id: "0AA"                       # Unique 3-char ID for this server
  description: "VNSnet IRC Hub Server"
  password: "flmrqfmrlfmeflrflrnrnelnrfl"                # CHANGE THIS! Share securely with leaf admins
  
  links:
    # No links needed for hub - just wait for leafs to connect
    # Leave this empty or omit entirely
