# IRC Server Configuration

server:
  name: "irc.example.com"
  host: "0.0.0.0"
  port: 6667
  tls:
    enabled: true
    port: 7000
    cert_file: "certs/server.crt"
    key_file: "certs/server.key"
  
  # Connection limits
  max_clients: 1000
  timeout_seconds: 300
  ping_interval_seconds: 60
  
  # Security
  rate_limit:
    enabled: true
    messages_per_second: 5
    burst: 10
  
  flood_protection:
    enabled: true
    max_lines_per_second: 10

# WebSocket support for browser-based IRC clients
websocket:
  enabled: true
  host: "0.0.0.0"
  port: 8080
  # Allowed origins for CORS (* allows all, or specify domains)
  allowed_origins:
    - "*"
    # - "http://localhost:8080"
    # - "https://example.com"
  tls:
    enabled: true
    cert_file: "server.crt"
    key_file: "server.key"
  
# Rate limiting
rate_limit:
  enabled: true
  messages_per_second: 5
  burst: 10

# Authentication
auth:
  enabled: false
  require_password: false

# Server operators
# Password should be bcrypt hashed
# Generate with: htpasswd -bnBC 10 "" yourpassword | tr -d ':\n' | sed 's/$2y/$2a/'
# Or use online bcrypt generator
operators:
  - name: "admin"
    password: "$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy"  # Example hash - CHANGE THIS!
  - name: "oper"
    password: "$2a$10$e0MYzXyjpJS7Pd94qMTnYu8qgx7Ky5.XYVzMSrVPXpLDXbDdSQT0W"  # Example hash - CHANGE THIS!

# Logging
logging:
  level: "info"  # debug, info, warn, error
  file: "logs/ircd.log"
  console: true

# Channel settings
channels:
  max_per_user: 10
  persist_topics: false

# Server Linking (Phase 7)
# Allows multiple IRC servers to connect together forming a network
linking:
  enabled: false  # Enable server linking
  host: "0.0.0.0"
  port: 7777      # Port for incoming server connections
  server_id: "0AA" # Server ID (SID): 3 chars [0-9][A-Z0-9][A-Z0-9]
  description: "IRC Server Hub"
  password: "ChangeThisLinkPassword!"  # Password for incoming links - CHANGE THIS!
  
  # Configured links to other servers
  links:
    # Example hub server
    # - name: "hub.example.net"
    #   sid: "1BB"
    #   host: "192.0.2.1"
    #   port: 7777
    #   password: "ChangeThisLinkPassword!"
    #   auto_connect: true
    #   is_hub: true
    
    # Example leaf server
    # - name: "leaf.example.net"
    #   sid: "2CC"
    #   host: "192.0.2.2"
    #   port: 7777
    #   password: "ChangeThisLinkPassword!"
    #   auto_connect: false
    #   is_hub: false
