# IRC Server Configuration - Server B (Leaf)

server:
  name: "leaf.example.net"
  host: "0.0.0.0"
  port: 6668
  tls:
    enabled: false
    port: 7001
    cert_file: "certs/server.crt"
    key_file: "certs/server.key"
  
  max_clients: 1000
  timeout_seconds: 300
  ping_interval_seconds: 60

# WebSocket support
websocket:
  enabled: true
  host: "0.0.0.0"
  port: 8081
  allowed_origins:
    - "*"
  tls:
    enabled: false

# Server operators
operators:
  - name: "admin"
    password: "$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy"  # "admin123"

# Logging
logging:
  level: "info"
  file: "logs/leaf.log"
  console: true

# Channel settings
channels:
  max_per_user: 10
  persist_topics: false

# Server Linking - Leaf Server
#
# This server acts as a LEAF - it CONNECTS to a hub server.
# This server will initiate the connection to the hub.
#
# To use:
# 1. Get connection details from your hub admin:
#    - Hub address (IP or domain)
#    - Hub link port
#    - Hub server_id
#    - Hub server name
#    - Link password
# 2. Set linking.enabled to true
# 3. Choose a unique server_id (NOT the same as hub! e.g., "002", "003", etc.)
# 4. Set linking.password to match the hub's password
# 5. Configure the "links" section below with hub details
# 6. Set auto_connect to true
#
# The leaf will automatically connect to the hub on startup!
#
linking:
  enabled: true
  host: "0.0.0.0"                       # Your server's link listener (in case hub connects back)
  port: 7778                             # YOUR link port (must be different from hub!)
  server_id: "1BB"                       # Unique 3-char ID (DIFFERENT from hub's "0AA"!)
  description: "Example IRC Leaf Server"
  password: "flmrqfmrlfmeflrflrnrnelnrfl"                # Must MATCH hub's password!
  
  links:
    # Configure the HUB server connection here
    - name: "hub.example.net"              # Hub's server.name (MUST MATCH EXACTLY!)
      sid: "0AA"                          # Hub's server_id (matches your hub!)
      host: "127.0.0.1"               # Hub's public IP or domain
      port: 7777                          # Hub's linking port
      password: "flmrqfmrlfmeflrflrnrnelnrfl"             # Hub's linking password (matches!)
      auto_connect: true                  # Automatically connect on startup
      is_hub: true                        # This is a hub server (keep as true)
